# Generated by Django 4.1.1 on 2022-10-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifytoken",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
