# Generated by Django 4.1.1 on 2022-10-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0003_remove_spotifytoken_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifytoken",
            name="access_token",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="spotifytoken",
            name="refresh_token",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
