# Generated by Django 4.1.1 on 2022-10-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="emotion", options={"ordering": ["name"]},),
        migrations.RenameField(
            model_name="emotion", old_name="genres", new_name="recommend_genres",
        ),
    ]
