# Generated by Django 4.1.1 on 2022-10-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_emotion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotion",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
