# Generated by Django 4.1.1 on 2022-10-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_emotion_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="emotion", name="image",),
        migrations.AddField(
            model_name="genre",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
