# Generated by Django 4.1.1 on 2022-10-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_emotion_image_genre_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotion",
            name="unified_code",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
