# Generated by Django 4.1.1 on 2022-10-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_emotion_unified_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emotion", old_name="unified_code", new_name="icon",
        ),
    ]
