# Generated by Django 4.1.1 on 2022-10-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_unified_code_emotion_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("mood", models.CharField(max_length=50)),
                ("genre", models.CharField(max_length=50)),
                ("artist", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
    ]
